txLog: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  topicName: !Env XTDB_TOPIC_NAME

storage: !Remote
  objectStore: !S3
    bucket: !Env XTDB_S3_BUCKET
    snsTopicArn: !Env XTDB_SNS_TOPIC
    prefix: "xtdb-object-store"
  localDiskCache: /var/lib/xtdb/buffers

metrics: !Prometheus
  port: 8080

modules: 
- !HttpServer
  port: 3000
- !PgwireServer
  port: 5432
