AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for setting up XTDB S3 object store and associated resources (XTDB user)

Parameters:
  S3BucketName:
    Type: String
    Description: Enter the desired name of the bucket which will contain the XTDB Object Store

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private

  S3AccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /
      Description: Policy that grants access to all resources needed for using the S3 bucket & it's changelog topic as an XTDB object store
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
            - 's3:ListBucket'
            - 's3:AbortMultipartUpload'
            - 's3:ListBucketMultipartUploads'
          Resource:
            - !Join [ '', [ 'arn:aws:s3:::', !Ref S3BucketName] ]
            - !Join [ '', [ 'arn:aws:s3:::', !Ref S3BucketName, '/*'] ]

Outputs:
  BucketName:
    Description: The name of the S3 Bucket
    Value: !Ref S3Bucket

  S3AccessPolicyArn:
    Description: ARN of the managed policy that has relevant S3 permissions
    Value: !Ref S3AccessPolicy
