AWSTemplateFormatVersion: '2010-09-09'
Description: An XTDB S3 object store and associated resources (IAM policy), see aws-dev-node.clj

Parameters:
  S3BucketName:
    Type: String
    Default: xtdb-object-store
    Description: Enter the desired name of the bucket which will contain the XTDB Object Store - default is 'xtdb-object-store'
  S3BucketDeletionPolicy:
    Type: String
    Default: Retain
    Description: Enter the deletion policy (default Retain) for the created bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !Ref S3BucketDeletionPolicy
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private

  XTDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:DeleteObject'
                - 's3:ListBucket'
              Resource:
                - !Join [ '', [ 'arn:aws:s3:::', !Ref S3BucketName ] ]
                - !Join [ '', [ 'arn:aws:s3:::', !Ref S3BucketName, '/*' ] ]

Outputs:
  BucketName:
    Description: The name of the S3 Bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'BucketName' ] ]
  XTDBPolicyArn :
    Description: ARN of the created XTDB managed policy (has relevant S3 permissions)
    Value: !Ref XTDBPolicy
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'XTDBPolicyArn' ] ]
