AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for setting up XTDB S3 object store and associated resources (XTDB user)

Parameters:
  S3BucketName:
    Type: String
    Default: xtdb-object-store
    Description: Enter the desired name of the bucket which will contain the XTDB Object Store - default is 'xtdb-object-store'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private

  XTDBIamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              AWS: !Ref AWS::AccountId
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:DeleteObject'
                - 's3:ListBucket'
                - 's3:AbortMultipartUpload'
                - 's3:ListBucketMultipartUploads'
              Resource:
                -  !Join [ '', [ 'arn:aws:s3:::', !Ref S3BucketName] ]
                -  !Join [ '', [ 'arn:aws:s3:::', !Ref S3BucketName, '/*'] ]

Outputs:
  BucketName:
    Description: The name of the S3 Bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'BucketName' ] ]
  XTDBRoleArn :
    Description: ARN of the created XTDB IAM Role (has relevant S3 permissions)
    Value: !GetAtt XTDBIamRole.Arn 
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'XTDBRoleArn' ] ]


