name: Auto Close Issues

on:
  pull_request:
    types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: FiV0/auto-close-fixed-issues@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # optional comment
          # comment: 'This issue was closed by #{{ pr }}.'
          # default ignore the pr merge to the default branch
          # ignore: true
