name: Docker images

on:
  workflow_call:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Standalone meta
        id: standalone-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/xtdb/xtdb-ea
          tags: |
            type=pep440,pattern={{version}}
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}
            type=edge,branch=main

      - name: AWS meta
        id: aws-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/xtdb/xtdb-aws-ea
          tags: |
            type=pep440,pattern={{version}}
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}
            type=edge,branch=main

      - name: Azure meta
        id: azure-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/xtdb/xtdb-azure-ea
          tags: |
            type=pep440,pattern={{version}}
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}
            type=edge,branch=main

      - name: Build Uberjar
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :docker:standalone:shadowJar :docker:aws:shadowJar :docker:azure:shadowJar

      - name: Push Standalone
        uses: docker/build-push-action@v5
        with:
          context: docker/standalone
          platforms: linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.standalone-meta.outputs.tags }}
          labels: ${{ steps.standalone-meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            XTDB_VERSION=${{ steps.standalone-meta.outputs.version }}

      - name: Push AWS
        uses: docker/build-push-action@v5
        with:
          context: docker/aws
          platforms: linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.aws-meta.outputs.tags }}
          labels: ${{ steps.aws-meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            XTDB_VERSION=${{ steps.aws-meta.outputs.version }}

      - name: Push Azure
        uses: docker/build-push-action@v5
        with:
          context: docker/azure
          platforms: linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.azure-meta.outputs.tags }}
          labels: ${{ steps.azure-meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            XTDB_VERSION=${{ steps.azure-meta.outputs.version }}
