name: XTDB Edge

on:
  workflow_dispatch:
  push:
    branches:
      - edge

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
